# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 68d6427dd45155c46651ed0db0453b62bda62ecf2d9b07dd0aa2e8f0b1daab1a82bf5d8544f953203984606b565e0a6f75629ab2e171461371adca6149596c4f

test:
  secret_key_base: 10f0c538e9152e863007353f374fea400ffdc170d8a19a7278951df44e5b3959e7d9820856ad54b9e696c022190b2856227b5de8d37bf3778a8e8879a0417f71

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
